name: CI Workflows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run-linters:
    uses: ./.github/workflows/run-linters.yml

  run-tests:
    uses: ./.github/workflows/run-tests.yml
