name: Run Docker Tests

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      UV_CACHE_DIR: ./.uv-cache
    strategy:
      matrix:
        test_target: [build-test, e2e-test]
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup
        with:
          dependency-command: 'uv sync --frozen'

      - name: Run tests
        run: |
          just ${{ matrix.test_target }}