name: Run Linters

on:
  workflow_call:

jobs:
  run-linters:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      UV_CACHE_DIR: ./.uv-cache
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup
        with:
          dependency-command: 'uv sync --only-group dev --frozen'

      - name: Run Linters
        run: just lint
